import { LocationGroup } from './types';

// Enhanced keywords for better AI company identification
export const AI_COMPANY_KEYWORDS = [
  'artificial intelligence',
  'machine learning',
  'deep learning',
  'neural network',
  'computer vision',
  'nlp',
  'language model',
  'llm',
  'generative ai',
  'ai platform',
  'ai infrastructure',
  'ml infrastructure',
  'ai research',
  'ai/ml',
  'ml ops',
  'mlops',
  'ai ops',
  'aiops',
  'autonomous systems',
  'robotics',
  'computer vision',
  'natural language processing',
  'reinforcement learning',
  'predictive analytics',
  'ai applications',
  'ai solutions',
  'ai tools',
  'ai software',
  'machine intelligence',
  'cognitive computing',
  'neural networks',
  'deep tech',
];

// Expanded engineering role keywords
export const ENGINEERING_ROLE_KEYWORDS = [
  'software engineer',
  'software developer',
  'full stack',
  'fullstack',
  'backend',
  'frontend',
  'machine learning engineer',
  'ml engineer',
  'ai engineer',
  'data engineer',
  'platform engineer',
  'infrastructure engineer',
  'systems engineer',
  'devops engineer',
  'site reliability engineer',
  'sre',
  'research engineer',
  'applied scientist',
  'technical lead',
  'engineering manager',
  'tech lead',
  'principal engineer',
  'staff engineer',
  'senior engineer',
  'software architect',
  'solutions architect',
  'application engineer',
  'python developer',
  'java developer',
  'cloud engineer',
];

// Rest of the constants remain the same...